language: python
script: tox
before_install:
  - openssl version
cache:
  directories:
  - ${HOME}/.cache
install:
- ./_travis/travis-install.sh
notifications:
  email: false
env:
  global:
    - GAE_PYTHONPATH=${HOME}/.cache/google_appengine
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=gae
sudo: false
